name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            # Salam, ${{ github.actor }}
            Issue bilen habardar edendigiňiz üçin sag boluň
          pr-message: |
            Message that will be displayed on users' first pr.
            Look, a `code block` for markdown
